export const OUTPUT = {
  code: 0,
  summary: {
    cost: 3571,
    unassigned: 0,
    delivery: [25],
    amount: [25],
    pickup: [0],
    service: 0,
    duration: 3571,
    waiting_time: 0,
    priority: 0,
    distance: 29609,
    computing_times: {
      loading: 14,
      solving: 22,
      routing: 10,
    },
  },
  unassigned: [],
  routes: [
    {
      vehicle: 1,
      cost: 1967,
      delivery: [13],
      amount: [13],
      pickup: [0],
      service: 0,
      duration: 1967,
      waiting_time: 0,
      priority: 0,
      distance: 16917,
      steps: [
        {
          type: "start",
          location: [106.66025161743164, 10.75906974788975],
          load: [13],
          arrival: 0,
          duration: 0,
          distance: 0,
        },
        {
          type: "job",
          description: "37D Thuận Kiều,Phường 12,Quận 5,Hồ Chí Minh",
          location: [106.6582775115967, 10.756708726602554],
          id: 9,
          service: 0,
          waiting_time: 0,
          job: 9,
          load: [12],
          arrival: 58,
          duration: 58,
          distance: 479,
        },
        {
          type: "job",
          description: "99O Phạm Hữu Chí,Phường 15,Quận 5,Hồ Chí Minh",
          location: [106.65544509887696, 10.75523307891171],
          id: 19,
          service: 0,
          waiting_time: 0,
          job: 19,
          load: [11],
          arrival: 119,
          duration: 119,
          distance: 912,
        },
        {
          type: "job",
          description: "945 Nguyễn Trãi,Phường 14,Quận 5,Hồ Chí Minh",
          location: [106.65493011474612, 10.752534733036687],
          id: 8,
          service: 0,
          waiting_time: 0,
          job: 8,
          load: [10],
          arrival: 196,
          duration: 196,
          distance: 1358,
        },
        {
          type: "job",
          description: "Cửa Hàng Cá Kiểng Tài,Phường 10,Quận 5,Hồ Chí Minh",
          location: [106.65965080261232, 10.751565009092835],
          id: 3,
          service: 0,
          waiting_time: 0,
          job: 3,
          load: [9],
          arrival: 294,
          duration: 294,
          distance: 2126,
        },
        {
          type: "job",
          description: "93/1B Võ Văn Kiệt,Phường 13,Quận 5,Hồ Chí Minh",
          location: [106.65814876556397, 10.748318519296627],
          id: 18,
          service: 0,
          waiting_time: 0,
          job: 18,
          load: [8],
          arrival: 388,
          duration: 388,
          distance: 3303,
        },
        {
          type: "job",
          description: "690/38D Nguyễn Duy,Phường 12,Quận 8,Hồ Chí Minh",
          location: [106.65935039520264, 10.744355224679536],
          id: 15,
          service: 0,
          waiting_time: 0,
          job: 15,
          load: [7],
          arrival: 601,
          duration: 601,
          distance: 6023,
        },
        {
          type: "job",
          description: "HẺM 486 Nguyễn Duy,Phường 10,Quận 8,Hồ Chí Minh",
          location: [106.66381359100345, 10.74473469131002],
          id: 4,
          service: 0,
          waiting_time: 0,
          job: 4,
          load: [6],
          arrival: 729,
          duration: 729,
          distance: 6984,
        },
        {
          type: "job",
          description: "308 Phạm Hùng,Phường 5,Quận 8,Hồ Chí Minh",
          location: [106.668963432312, 10.740054569542045],
          id: 16,
          service: 0,
          waiting_time: 0,
          job: 16,
          load: [5],
          arrival: 893,
          duration: 893,
          distance: 8425,
        },
        {
          type: "job",
          description:
            "Công Ty TNHH Vật Liệu Xây Dựng Trường Thái Hưng,Phường 4,Quận 8,Hồ Chí Minh",
          location: [106.67797565460207, 10.741530291441832],
          id: 25,
          service: 0,
          waiting_time: 0,
          job: 25,
          load: [4],
          arrival: 1097,
          duration: 1097,
          distance: 9836,
        },
        {
          type: "job",
          description: "Tiệm Tóc Quỳnh Ty,Phường 4,Quận 8,Hồ Chí Minh",
          location: [106.67891979217532, 10.743638453076365],
          id: 12,
          service: 0,
          waiting_time: 0,
          job: 12,
          load: [3],
          arrival: 1165,
          duration: 1165,
          distance: 10232,
        },
        {
          type: "job",
          description: "Spa Đoan Thanh,Phường 3,Quận 8,Hồ Chí Minh",
          location: [106.68273925781252, 10.745029831692918],
          id: 24,
          service: 0,
          waiting_time: 0,
          job: 24,
          load: [2],
          arrival: 1391,
          duration: 1391,
          distance: 11642,
        },
        {
          type: "job",
          description: "652 Phạm Thế Hiển,Phường 4,Quận 8,Hồ Chí Minh",
          location: [106.67578697204593, 10.745198483210745],
          id: 5,
          service: 0,
          waiting_time: 0,
          job: 5,
          load: [1],
          arrival: 1526,
          duration: 1526,
          distance: 12774,
        },
        {
          type: "job",
          description: "27/7 Phạm Hùng,Phường 9,Quận 8,Hồ Chí Minh",
          location: [106.6693925857544, 10.747475269480445],
          id: 17,
          service: 0,
          waiting_time: 0,
          job: 17,
          load: [0],
          arrival: 1711,
          duration: 1711,
          distance: 14475,
        },
        {
          type: "end",
          location: [106.66025161743164, 10.75906974788975],
          load: [0],
          arrival: 1967,
          duration: 1967,
          distance: 16917,
        },
      ],
      geometry:
        "gkt`A{a_jSFAXI`A[z@YRvADZTfBd@nDFJLdA|AIlBIr@EfCG`@jFf@`FNjBBJ@L@PD`@BPDj@nCYdBSVdCZCtD?C_BCeAAoAA[?_AAk@?SAg@AgAAoACoAAk@GgCAQAQCgCC{AxB?pAA?pAxA?R?r@DbAFd@HXFNe@Hw@?i@EYYw@c@w@[w@Me@Ik@Cm@@WFq@Ji@Vu@N[Xc@Za@`@I^ER?n@hCpAjF`BdHfAnEl@~BDNb@~AX~@~AvD|CfGlEnJhGhMRKwG}MkAmCkE}IeCqFc@iAq@}BHC]oAgCaKx@OfAKp@@tBLb@DTBNHJJDJDr@DPh@j@r@v@z@t@v@f@V`@R`@JCk@gAKUnAe@nAk@oAj@oAd@Qa@y@kB_@_AIUGOGOM]HUFGrAm@TO\\[LUL]ZiAFUZy@Pc@N[DO?]Gu@|@Mv@Ix@Ix@KdAKYiCeAJw@Fy@Jx@Kv@GYgDcA@m@A{@Ay@?Iu@O{AQuAQsBGk@CSM_AIs@Ks@Eg@OwAGe@Is@Ik@lFLrF@tJErBChA@dACh@GXE\\ERENCn@WhB}@`Aq@nBmAlAu@|@q@rAaALIIMKFQN]gA]aAY_AoAmE}A_DqAyCcCeGsD_J{@oCgARm@~@l@_AfASeAgDyAXmBHmDQlDPlBIxAYcBmFq@qBmBoFk@gAW]O]bAs@t@aAl@w@j@u@qBqDWJkAf@u@Z{Ar@}FhCm@XuAn@z@rB[s@_@_Aq@XcAb@cAb@c@Ta@RuAr@qB|@}@`@`CpFv@dBDH~CjHtBzEDLb@`A\\v@~@tBVl@BDRh@L`@Z|@Rh@\\fANf@Pn@FVLr@^hBb@`CNfAPhAFp@D^Db@Jv@Fr@NlADb@Df@rAOnBSpAMfAKf@|EHd@gNBuD?gEGiBMmEK_@AGAyCMmBEgCE}AGw@GaFSyDIiAEM?OD{ACc@KgFMqACyAAm@AwDEQ@wAPaBTiBVsEn@eBTWGODEDEJ?H@FFHLFH?VtCBRXvBbArIN|AJv@d@nEj@rEXdBFdANdA^rD}Ah@y@TG@",
    },
    {
      vehicle: 2,
      cost: 1604,
      delivery: [12],
      amount: [12],
      pickup: [0],
      service: 0,
      duration: 1604,
      waiting_time: 0,
      priority: 0,
      distance: 12692,
      steps: [
        {
          type: "start",
          location: [106.66025161743164, 10.75906974788975],
          load: [12],
          arrival: 0,
          duration: 0,
          distance: 0,
        },
        {
          type: "job",
          description:
            "Ủy Ban Mặt Trận Tổ Quốc Quận 5,Phường 8,Quận 5,Hồ Chí Minh",
          location: [106.66681766510013, 10.756034145696845],
          id: 2,
          service: 0,
          waiting_time: 0,
          job: 2,
          load: [11],
          arrival: 142,
          duration: 142,
          distance: 1155,
        },
        {
          type: "job",
          description: "43 An Duong Vuong street,Phường 8,Quận 5,Hồ Chí Minh",
          location: [106.670937538147, 10.756118468392576],
          id: 23,
          service: 0,
          waiting_time: 0,
          job: 23,
          load: [10],
          arrival: 202,
          duration: 202,
          distance: 1727,
        },
        {
          type: "job",
          description: "409/30 Nguyễn Trãi,Phường 7,Quận 5,Hồ Chí Minh",
          location: [106.67368412017824, 10.75460065626278],
          id: 14,
          service: 0,
          waiting_time: 0,
          job: 14,
          load: [9],
          arrival: 303,
          duration: 303,
          distance: 2331,
        },
        {
          type: "job",
          description: "448/15 Trần Hưng Đạo,Phường 2,Quận 5,Hồ Chí Minh",
          location: [106.682825088501, 10.756371436338306],
          id: 13,
          service: 0,
          waiting_time: 0,
          job: 13,
          load: [8],
          arrival: 476,
          duration: 476,
          distance: 3667,
        },
        {
          type: "job",
          description: "90/15 Lê Hồng Phong,Phường 2,Quận 5,Hồ Chí Minh",
          location: [106.67861938476564, 10.756708726602554],
          id: 6,
          service: 0,
          waiting_time: 0,
          job: 6,
          load: [7],
          arrival: 566,
          duration: 566,
          distance: 4405,
        },
        {
          type: "job",
          description: "130 Đường Trần Nhân Tôn,Phường 2,Quận 10,Hồ Chí Minh",
          location: [106.67445659637453, 10.765646781123572],
          id: 22,
          service: 0,
          waiting_time: 0,
          job: 22,
          load: [6],
          arrival: 715,
          duration: 715,
          distance: 5625,
        },
        {
          type: "job",
          description: "42/11 Hồ Thị Kỷ,Phường 1,Quận 10,Hồ Chí Minh",
          location: [106.67763233184816, 10.764255497600209],
          id: 1,
          service: 0,
          waiting_time: 0,
          job: 1,
          load: [5],
          arrival: 818,
          duration: 818,
          distance: 6443,
        },
        {
          type: "job",
          description: "Bãi Giữ Xe,Phường 3,Quận 10,Hồ Chí Minh",
          location: [106.67188167572025, 10.761641553611933],
          id: 11,
          service: 0,
          waiting_time: 0,
          job: 11,
          load: [4],
          arrival: 938,
          duration: 938,
          distance: 7372,
        },
        {
          type: "job",
          description: "HẺM 545 3 Tháng 2,Phường 8,Quận 10,Hồ Chí Minh",
          location: [106.66664600372316, 10.766616459780574],
          id: 7,
          service: 0,
          waiting_time: 0,
          job: 7,
          load: [3],
          arrival: 1097,
          duration: 1097,
          distance: 8473,
        },
        {
          type: "job",
          description: "669 Đường 3/2,Phường 14,Quận 10,Hồ Chí Minh",
          location: [106.66574478149416, 10.76729101700582],
          id: 21,
          service: 0,
          waiting_time: 0,
          job: 21,
          load: [2],
          arrival: 1165,
          duration: 1165,
          distance: 8808,
        },
        {
          type: "job",
          description:
            "Trung Tâm Dịch Vụ Thể Dục Thể Thao,Phường 15,Quận 11,Hồ Chí Minh",
          location: [106.65900707244875, 10.765478141038593],
          id: 10,
          service: 0,
          waiting_time: 0,
          job: 10,
          load: [1],
          arrival: 1327,
          duration: 1327,
          distance: 10271,
        },
        {
          type: "job",
          description: "1119 3 Tháng 2,Phường 6,Quận 11,Hồ Chí Minh",
          location: [106.65462970733644, 10.760756180347798],
          id: 20,
          service: 0,
          waiting_time: 0,
          job: 20,
          load: [0],
          arrival: 1485,
          duration: 1485,
          distance: 11697,
        },
        {
          type: "end",
          location: [106.66025161743164, 10.75906974788975],
          load: [0],
          arrival: 1604,
          duration: 1604,
          distance: 12692,
        },
      ],
      geometry:
        "gkt`A{a_jSFAXI`A[z@YRvAJASwAa@uDpBa@`Cc@`B[h@K`Dm@t@M^Ga@aEOsAu@qGy@_FQ_BaAgIe@qE@S?Q}@sInBC_@@oA@CQK}@zAKT?xAC|@AnACn@@a@wD]_DbAMZEZEZE??RMREKe@c@{AhEq@RCm@qDe@iC]iBs@iDgAwFi@sC_@aCGg@MgASeB_@wBwAaIEOQBDPb@~BDNHh@d@fC^vBf@hEBP\\xBf@rCwD`Am@NwBl@}@PXq@Yp@{@TEOCKeA\\{A^mDz@kFpAyA^uFxAwA`@kCr@_Bb@{@Ti@Ni@L}@TmBh@}A`@?JVxBNlAaAL]DcCXg@FgALKGa@U{@m@FO@MAUISQQ\\uApAyF\\BVA\\GNMzBm@`@O~@Yt@SbBg@|Ac@r@QhBg@z@Wz@zAp@nA|@`BDHz@vAFLrBlDh@bA?n@J~@TfBPzA_Df@VlAYDTvB@BBXOTg@JWD}B^XtC\\rCb@zCLv@RnAo@He@HUBq@JmANuC^kCb@m@Fs@HOBq@HgANBTHx@Jt@aAN}@L_ALWDa@Fy@Jo@DC@y@cBIS[DJR^v@nArCR`@~@rBJTJLVf@vA~CHP\\z@Vh@^|@l@tA`BrDh@lAl@rATh@t@bBNZAXEPaHnAwBb@cCd@aEv@@JxDu@vAWZhBJTFBnAA^D_@EoA@GCKU[iBtE{@zBc@|Ba@RDXNfFhLN\\n@|AHPNZ~AlDLVVl@Vj@z@lBZr@^x@FPh@jAl@tAJVPCKWUg@Ug@Se@Yo@IQSg@EKu@eBIOw@gBIQw@aBSe@w@mBIQs@}A}BaF~Ag@pBk@XKb@K~Ai@f@On@Sr@SXKb@Ot@SlA]vA_@NE",
    },
  ],
};

export const DEV_OUTPUT = {
  code: 0,
  routes: [
    {
      amount: [5],
      cost: 9786,
      delivery: [5],
      distance: 176498,
      duration: 9786,
      geometry:
        "u~f`AsntfSk@VUDkCVGeAK{AcA}NUyDMqA[qCu@oHcEkYQyAg@gELSVsERyDC]JmCp@uRBsA?i@O}HOwFG[KYeAeCqJsVGUAULyCDg@Hc@^gATa@Za@l@o@jEuDf@]x@e@~@e@~CsAnAa@~CgAn@O`@GlLoAhGu@fC_A~@m@`@c@To@Nm@xAiHB_@?_@EeDRmE^sE|@}Op@eJ`CeWn@{DfBiIf@mCHo@Be@Aa@E_@y@aCcLmYS]w@eAa@g@wK_M_AsA[e@O_@Kk@q@{GE_ACuADw@z@oGVm@`@k@nDgDVUz@c@tJ{Dd@Oh@OpGeAtB_@rJ}AxKwBvAYv@Qz@KjFQt@ErE_AfMkCdAQpAQxHw@Z?`@BjBN[wAe@yBeDkL{BkIA_@Fc@hA_CxCiGxA{CzChBh@XrAn@fA`@`Bb@dBVz@Jv@@`FI~BKzQo@zEOjL_@hJ]nK]fEKt\\t@dFNjABfCFjaA|BBoEBaPMwKKaBKqBBaBDkB@u@Bw@LcAXkAn@gBDSJm@Fy@DkAKiG?cCFwATsEpAgUZiE\\kCFgA]eNIqHa@a\\u@ke@OcJI}Gi@aSGeF@cBCuOBwMBsIFwh@Dii@?}P?cA@m@@yD?MDyFLk@vKg[pSsk@t@qBjL}[jSkk@dPkd@lAiDdEsLr@{Bl@_DVaA^_Al@sAn@yAp@gAj@mAPa@vBiGfA}ClAiD|F}OnAgDLa@rPke@JYhIqUfF}N|JuXzBmGJWVw@lAuD|C}Iz@cCp@wBHa@X_FHm@Ne@Pa@f@o@z@{@vAmAjCsBj@_@fFiDv@i@RQnAwAf@o@vBoC|D}FjDsFrAaCz@wAnAkC~EqK~EiKVg@X]b@_@r@a@vDiAtKcDpPoFnIqCbC}@t@SlAQnAKzDe@`Fw@vCq@hTkEp@Sp@[fAk@p@a@fI_GxG{DpQgKlCgBtCuBtCsBnDmBlD_BnLmFjPoHpB_ApAq@`@]`@c@jAkBbDqFt@oAlBwDtAuCxBsEzEgKr@qATUpHkF`Ae@j@MtDc@b@Qj@a@XYT_@Ja@DYAoCE}ASsF?a@B}@Vw@l@iApLiRf@SrE_HRCb@BzMfKpDrCd@`@RVR|A@^Gr@Of@Yh@QPe@\\QJm@No@FW?}@IYEqBo@}FoEcImG_CiB_BoAwFgEaBoAqKyI}AqAsE{Dc\\iWun@mf@cOsLeJgI{B_CwGwGko@yp@eHmGoh@ya@qDuCwBiBsDiD{ByBmHqH{@{@{VeWsGuG{EyEkJoJeDkDiFiFeNwMuEcEyMyL{RuRmEqEqAqAk@m@eXsXqUwU{A_BgCiC}RwSwFwGsCoDiC_DgKuNeCmDcLsP}BiDsFcIiOeUyHcLaIiLcLyOmJkNaDuEsB}CiDgFiAiBo@eA{CoFwBcEwByEeC_GyBeG}A_F{AkFi@wB}GgYyOcq@{EgUmBeKaCeOoD_W{CqUaIil@uBwMcAmFsA}F}DsOcEeMc@oA}CqIoBiFwAgEuAaEqP{d@aEgLaX}t@eCkHoAwDw@qCmBmHkAoFyA_Ig@kCa@aCq@wDeAyFoDkSuA{Io@kEIe@]{Dq@qFUmBwB_RwB}Q_Isq@[sCS}Aq@aGCUiEy^e@iEQsAIe@WeBAeADCLQDU@KCUKSQOSGS?SBQJIFmCq@iH_B_@BwA[}M{CyCo@yBc@OEuIoAcCYmBOeAAkBDeLP_A@iD?kAIeD{@uDcAgASoFk@sMoAw@KeAMaCg@cBWyD_@eAIsCYSMiDw@{@a@k@i@kAsBY]m@e@a@SmAYkAQq@Ye@a@a@m@UO_AoCkCoG_EiKi@wAMYeAgCwCsH}BeGyAuDs@kBgK{WaIuSuBqFiC{GkD{HaE_J_EsIsEyJiDaI[s@qBoEsAuCw@_BoEmIcGqL}@cBcCyEqBcEkEgI}EkJkKoSUNMH[Tq@^OF_Ad@eAh@KD{DlBgErBOJ]Ny@b@oCvASPENc@Ca@BaCPa@Bg@DkBNy@FULYDgAHmE\\Q@o@?YCw@IYGeEk@iCY{@KqAOk@Eo@GWCsAMSKq@K}@Ki@I_AMw@IqC[_AIwAOg@EeCYu@G}@Km@GmAMaBK_BQaBO{BU_D_@AP~C`@rAJhAL`AHKbAIn@ENYhAKhAC`@AVCXAdA?nA`@?p@ALvCF`Bv@Cv@C~@G_AFw@BGcBCg@GuARERg@u@]}AQa@Cq@Es@CaACqBEg@Aq@Aw@AO?c@C}@uD_@eAu@qAc@s@MKmAiBCGS[GMKQg@y@OYGI_@q@U_@MU]m@a@s@`BiDd@}@fDwHfC}Fh@^`Ep@jC^fATh@Jl@Lj@JbBT^FbANhC`@@KLcATe@LM]s@_AsBq@wADWJQzCPn@D~CNxAHz@D@OI{@OyACUOeAG[M_Aa@_DCU]cDm@yEOqAI{@CS[kCUsBOgBMeABMe@oDUiBEYSwAa@uDpBa@`Cc@`B[h@K`Dm@t@M^Ga@aEOsAu@qGy@_FsAgLe@qE@S?Q}@sICQK}@SyAK_AIi@Gi@I_ASkBJGFKC]GGKCw@{BkAcEOc@a@oA]gASm@y@gCCKg@cBc@wAGOMc@Oa@Qk@c@uAOk@So@yAmFGS_@qAi@iBQq@q@_CCIjEoAzAa@l@OtF}At@Uz@UhFcBXdA|@vEDPPEdG_Br@OjBI|Cp@hBTp@HhAPRDVDHe@WESEmK}@zPtBDZ^tFDd@Fz@X~DRnBThAP|@ZdB\\xAH\\r@hCTn@d@bALR`EpGdBjCPVz@pAJZDLJt@Hn@RbBHv@NhA@HJ`ABPFd@@PBPPxAHl@XbCD^D\\BJBRJz@Fd@@PHp@D^mEK_@AaDOmBEgCE}AGMQAMdA}J?]CM~AkGR_BUAU~A[rAyBjIMfAYvEk@vJWfDKnB?dADhAFx@LhAbAbEHZLh@Nj@n@hCpAjF`BdHfAnEr@nCb@~AX~@~AvD|CfGlEnJhGhM|BtEjDlHrGnM\\p@rX`i@nGdMv@|ApFnK~FpLtAtCdCvFb@bAtCbGnEzJtDtIlI`R~C`I|@zBdK~WhJ~UrAjDv@rB|CbIvCtHfAfCp@pBrIdTbDlIjB`FXfAH|@El@]j@QLYFY?[GSMQUIUA_@Fa@JSTShBa@`Fj@xE^xFn@bBNvCXf@Dr@FtFLpGl@pALtCXlGn@jAT`I|Bp@JjABnE?fLSpCCzEb@dIfAdANND`NvCbJrBLVlEnAp@L`ARhAz@XVh@r@`@p@l@dBLXPzAT|BnE~_@x@bHf@nErGpj@p@hGrFvd@TlBRxA|@|IHb@jAbI^zBbDfR~DzTf@fCxAbIvAnGxAxF~@fDrAbEzBpG|HjTxBbGnJ|WlKtYjAbD|JlX`HnRrC`Id@xAjAvDbC|IjBhHp@rCx@fEh@tCb@hC~@`GjCfRdAfI~Ibq@|@pG`AtGtAnIjAvG~@~EbA|E~CtNxMzj@~AbH~BvK|AtGd@pBzAjF|A`FpAjDh@xAdBdEvCtGbDfGpBnDp@dAfAhBhDdFtB~CnO`UbLxO`IhLxHbLhOdUrCbE|A~B~BhDbLrPdClDfKvN~GnIvFxG|RtSdCjCpXvX`XpX~B`ClEpEvMrMbD`DpT~RbNtMnBnBdHjHdJhJdGbGd^p^z@z@lHrH|BxBrDhDxBhBpDtClh@xa@dHjGjo@xp@tGvGzB~B~BzBjV`Stn@lf@b\\hWpBbB`EhDnKxIdBpArFfE~AlAz@n@bMbKjAbBPd@Lf@D`@?\\QpCBh@BNN^JNTV`@R^Hl@Af@Kh@]rAaBzEqGZk@Pm@Fs@Eu@Ou@KWS]UWuEsDmDqCsHcG[SMGKIKNwF`JyErHeG~JWv@C~ARrFD|A@nCEXK`@U^YXk@`@c@PuDb@k@LaAd@qHjFUTs@pA{EfKyBrEuAtCmBvDu@nAcDpFkAjBa@b@a@\\qAp@qB~@kPnHoLlFmD~AoDlBuCrBuCtBmCfBqQfKyGzDgI~Fq@`@gAj@q@Zq@RiTjEwCp@aFv@{Dd@oAJmAPu@RcC|@oIpCmEtAyV|HwDhAs@`@c@^Y\\Wf@_FhKqBfE}DtI{@vAsA`CkDrF}D|FwBnCg@n@oAvASPw@h@gFhDk@^kCrBwAlA{@z@g@n@Q`@Od@Il@Y~EI`@q@vB{@bC}C|ImAtDWv@KVOb@kKtYeIfUiIpUKXsJzW_EnLM`@oAfD}F|OmAhD_EfLQ`@k@lAq@fAo@xAm@rA_@~@W`Am@~Cs@zBeErLmAhDePjd@w`@hhAu@pBqSrk@wKf[Mj@El@?jE?LAxDAl@?bA?|PEhi@Gvh@CrICvMBtOAbBFdFh@`SH|GNbJt@je@`@`\\HpH\\dNGfA]jC[hEqAfUUrEGvA?bCJhGEjAGx@Kl@ERo@fBYjAMbACv@At@EjBC`BJpBJ`BLvKC`PCnEkaA}BgCGkACeFO}b@i@oK\\iJ\\kL^{EN{Qn@_CJaFHw@A{@KeBWaBc@gAa@sAo@i@Y{CiByAzCyChGiA~BGb@@^zBjIdDjLd@xBZvAkBOa@C[?yHv@qAPeAPgMjCsE~@u@DkFP{@Jw@PwAXyKvBsJ|AuB^qGdAi@Ne@NuJzD{@b@WToDfDa@j@Wl@{@nGEv@HtCp@zGJj@N^Zd@~@rAvK~L`@f@v@dAR\\bLlYx@`CD^@`@Cd@In@g@lCgBhIo@zDaCdWq@dJ}@|O_@rESlEDdD?^C^yAhHOl@Un@a@b@_Al@gAd@_AXiGt@mLnAa@Fo@N_DfAoA`@_DrA_Ad@y@d@g@\\kEtDm@n@[`@U`@_@fAIb@Ef@MxC@TFTpJrVdAdCJXFZNvFN|H?h@CrAq@tRKlCMXUzDUtEBRf@fEPxAbEjYt@nHZpCLpATxDbA|NJzAFdAjCWTEj@W",
      pickup: [0],
      priority: 0,
      service: 0,
      steps: [
        {
          arrival: 0,
          distance: 0,
          duration: 0,
          load: [5],
          location: [106.112456, 10.684922],
          type: "start",
        },
        {
          arrival: 4395,
          distance: 82298,
          duration: 4395,
          id: 4,
          job: 4,
          load: [4],
          location: [106.640521, 10.758969],
          service: 0,
          type: "job",
          waiting_time: 0,
        },
        {
          arrival: 4613,
          distance: 84243,
          duration: 4613,
          id: 5,
          job: 5,
          load: [3],
          location: [106.649763, 10.760691],
          service: 0,
          type: "job",
          waiting_time: 0,
        },
        {
          arrival: 5090,
          distance: 88743,
          duration: 5090,
          id: 2,
          job: 2,
          load: [2],
          location: [106.681332, 10.760353],
          service: 0,
          type: "job",
          waiting_time: 0,
        },
        {
          arrival: 5248,
          distance: 90147,
          duration: 5248,
          id: 3,
          job: 3,
          load: [1],
          location: [106.68377, 10.752257],
          service: 0,
          type: "job",
          waiting_time: 0,
        },
        {
          arrival: 5401,
          distance: 91388,
          duration: 5401,
          id: 1,
          job: 1,
          load: [0],
          location: [106.678517, 10.749881],
          service: 0,
          type: "job",
          waiting_time: 0,
        },
        {
          arrival: 9786,
          distance: 176498,
          duration: 9786,
          load: [0],
          location: [106.112456, 10.684922],
          type: "end",
        },
      ],
      vehicle: 1,
      waiting_time: 0,
    },
  ],
  summary: {
    amount: [5],
    computing_times: {
      loading: 27,
      routing: 4,
      solving: 10,
    },
    cost: 9786,
    delivery: [5],
    distance: 176498,
    duration: 9786,
    pickup: [0],
    priority: 0,
    service: 0,
    unassigned: 0,
    waiting_time: 0,
  },
  unassigned: [],
};
